const names = [
    'P100',
    'PF120',
    'P200',
    'P400',
    'P4K',
    'A200',
    'A300',
    'WPEncode',
    'WPDecode',
    'Studio',
    'Mini',
    'FlexIn',
    'FlexOut',
    'HDMISDI4K',
    'Quad4K',
];

module.exports = {
    names,
    P100: require('./P100.js'),
    PF120: require('./PF120.js'),
    P200: require('./P200.js'),
    P400: require('./P400.js'),
    P4K: require('./P4K.js'),
    A200: require('./A200.js'),
    A300: require('./A300.js'),
    WPEncode: require('./WPEncode.js'),
    WPDecode: require('./WPDecode.js'),
    Studio: require('./Studio.js'),
    Mini: require('./Mini.js'),
    FlexIn: require('./FlexIn.js'),
    FlexOut: require('./FlexOut.js'),
    HDMISDI4K: require('./HDMISDI4K.js'),
    Quad4K: require('./Quad4K.js'),
};
